[
	{
		id: 'RT3080',
		invoice_date: 'Tue Sep 1 2002',
		invoice_due_date: 'Tue Sep 21 2021',
		description: 'Re-branding',
		client_name: 'Jensen Huang',
		client_email: 'jensenh@mail.com',
		status: 'Paid',
		user_street_address: '19 Union Terrace',
		user_city: 'London',
		user_post_code: 'E1 3EZ',
		user_country: 'United Kingdom',
		client_street_address: '106 Kendell Street',
		client_city: 'Sharrington',
		client_post_code: 'NR24 5WQ',
		client_country: 'United Kingdom',
		invoice_items: [{ name: 'Brand Guidelines', quantity: 2, price: 500 }],
	},
	{
		id: 'RT3080z',
		invoice_date: 'Tue Sep 1 2022',
		invoice_due_date: 'Tue Sep 21 2021',
		description: 'Logo Work',
		client_name: 'Gabe Newl',
		client_email: 'hammer@mail.com',
		status: 'Pending',
		user_street_address: '39 Cres Terrace',
		user_city: 'Vancouver',
		user_post_code: 'E1 3EZ',
		user_country: 'Canada',
		client_street_address: '26 Gaz Street',
		client_city: 'Blemdale',
		client_post_code: 'NR24 5WQ',
		client_country: 'United Kingdom',
		invoice_items: [
			{ name: 'Brand Guidelines', quantity: 2, price: 250 },
			{ name: 'Website Work', quantity: 2, price: 500 },
		],
	},
	{
		id: '',
		status: 'Draft',
		user_street_address: '',
		user_city: '',
		user_post_code: '',
		user_country: '',
		client_name: '',
		client_email: '',
		client_street_address: '',
		client_city: '',
		client_post_code: '',
		client_country: '',
		invoice_date: '2021-09-21T23:54:55.319Z',
		invoice_due_date: '2021-09-21T23:54:55.319Z',
		description: '',
		invoice_items: [
			{ name: 'Banner Design', quantity: 1, price: 156 },
			{ name: 'Banner Design', quantity: 1, price: 156 },
		],
	},
];
